from abc import ABC, abstractmethod
import subprocess

from models import TVStatus


class RemoteBackend(ABC):
    """
    Interface used by the Church TV controller.
    """

    @abstractmethod
    def get_status(self) -> TVStatus:
        raise NotImplementedError

    @abstractmethod
    def start(self) -> str:
        raise NotImplementedError

    @abstractmethod
    def restart_display(self) -> str:
        raise NotImplementedError

    @abstractmethod
    def reboot(self) -> str:
        raise NotImplementedError

    @abstractmethod
    def shutdown(self) -> str:
        raise NotImplementedError

    @abstractmethod
    def get_screenshot(self) -> bytes:
        raise NotImplementedError

    @abstractmethod
    def reset_hdmi(self):
        raise NotImplementedError


class SSHRemoteBackend(RemoteBackend):
    """
    Communicates with the Church TV PC using SSH.

    SSH key authentication is expected to already be configured.
    """

    def __init__(
        self,
        host="10.0.0.20",
        user="wmc",
        control_command="/usr/local/sbin/church-tv-control",
        mac_address="50:65:f3:40:a4:05",
    ):
        self.host = host
        self.user = user
        self.control_command = control_command
        self.mac_address = mac_address

    def _run(self, *arguments):
        command = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", "ConnectTimeout=5",
            f"{self.user}@{self.host}",
            "sudo",
            "-n",
            self.control_command,
            *arguments,
        ]

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=15,
        )

        if result.returncode != 0:
            error = result.stderr.strip()

            if not error:
                error = (
                    f"Remote command failed "
                    f"with exit code {result.returncode}."
                )

            raise RuntimeError(error)

        return result.stdout.strip()

    def _run_bytes(self, command):
        result = subprocess.run(
            command,
            capture_output=True,
            timeout=30,
        )

        if result.returncode != 0:
            error = result.stderr.decode(
                "utf-8",
                errors="replace",
            ).strip()

            if not error:
                error = (
                    f"Remote command failed "
                    f"with exit code {result.returncode}."
                )

            raise RuntimeError(error)

        return result.stdout

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------

    def get_status(self) -> TVStatus:
        try:
            output = self._run("status")

        except Exception as exc:
            return TVStatus(
                tv_online=False,
                church_tv_running=False,
                openlp_reachable=False,
                message=str(exc),
            )

        values = {}

        for line in output.splitlines():
            if ":" not in line:
                continue

            key, value = line.split(":", 1)
            values[key.strip()] = value.strip()

        return TVStatus(
            tv_online=True,
            church_tv_running=(
                values.get("DISPLAY") == "RUNNING"
            ),
            openlp_reachable=(
                values.get("OPENLP") == "ONLINE"
            ),
            message="",
        )

    # ------------------------------------------------------------------
    # Power
    # ------------------------------------------------------------------

    def start(self) -> str:
        result = subprocess.run(
            [
                "/usr/bin/wakeonlan",
                self.mac_address,
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )

        if result.returncode != 0:
            raise RuntimeError(
                result.stderr.strip()
                or "Wake-on-LAN command failed."
            )

        return "Wake-on-LAN signal sent to TV computer."

    def restart_display(self) -> str:
        return self._run("restart")

    def reboot(self) -> str:
        return self._run("reboot")

    def reset_hdmi(self):
        return self._run("reset-hdmi")

    def shutdown(self) -> str:
        return self._run("shutdown")

    # ------------------------------------------------------------------
    # TV preview
    # ------------------------------------------------------------------

    def get_screenshot(self) -> bytes:
        """
        Capture the TV PC's graphical desktop and return it as PNG data.

        The screenshot is generated by the controlled
        church-tv-control script on the TV PC and streamed directly
        back over SSH.
        """

        command = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", "ConnectTimeout=5",
            f"{self.user}@{self.host}",
            "sudo",
            "-n",
            self.control_command,
            "screenshot",
        ]

        data = self._run_bytes(command)

        if not data.startswith(b"\x89PNG\r\n\x1a\n"):
            raise RuntimeError(
                "The TV screenshot could not be captured."
            )

        return data
